### PR TITLE
QFix - battery value blinkin TEF6686_ESP32.ino

### PR DESCRIPTION
**Pull request by Overland-DX**
It looks like this overrides the values in percentage and voltage display when they reach certain values.
This applies to the bug where the battery value indicator are blinking.
I am unable to provoke the problem after removing this line. Delete if I'm completely off track.

### CODE REVIEW

**Comment by Overland-DX** [comment]
Line 157:
Since scan in AM is not implemented yet, it is probably best that this is selected on the SW band until everything works.

**Comment by PE5PVB** [comment]
About blinking. That was already fixed. This is not the way to fix it, because it will give a problem with the old battery view

**Comment by Overland-DX** [comment]
I still have the bug here, around 4.0 volts, then the values disappear and don't come back until the values are updated manually or automatically. It is still the background that goes over the values, because when I move the values out or partially out of the battery frame, they work fine.
I can report the problem instead. :)

**Comment by PE5PVB** [comment]
OK. I'll check this, fix needs to be done another way.

**Comment by PE5PVB** [comment]
I fixed it another way

**Comment by Overland-DX** [comment]
> I fixed it another way

Nice, thanks 👍

**Pull request closed without merging**
