### PR TITLE
Centered PI value in order ?? not to wrap

### PR DESCRIPTION
**Pull request by MCelliotG**

### CODE REVIEW

**Comment by PE5PVB** [comment]
I don't like the way of centering the PI code. This will cause a lot of flickering when RDS reception is bad. I'll look into another solution.

**Comment by andimik** [comment]
I don't expect flickering because the numbers and letters have different widths even now.

**Comment by MCelliotG** [comment]
> I don't like the way of centering the PI code. This will cause a lot of flickering when RDS reception is bad. I'll look into another solution.

But did you try it to see how it looks? Out of all my tests this looked the best, I didn't see any flickering at all!

**Comment by PE5PVB** [comment]
OK. I've applied it.

**Pull request merged**
