### PR TITLE
Language names in German translated

### PR DESCRIPTION
**Pull request by andimik**
- all defined language names translated
- Moldovian -> Moldavian (typo)
- added FM to band edges

### CODE REVIEW

**Comment by PE5PVB** [comment]
Sorry, due to memory problems it's not possible to have all languages translated to each language in the code. I changed the Moldavian typo. Can you please advice me again on added FM to band edges?

**Comment by andimik** [comment]
I mean I have added the word "FM"  to the menu. Otherwise one could think the lower band edge is LW...

**Comment by PE5PVB** [comment]
OK. Is it still in the repository now? Then it's ok.

**Comment by andimik** [comment]
Just the text is different. Same number, no new line of course...

**Pull request closed without merging**
