### PR TITLE
Upper icon small rearrangement, battery values

### PR DESCRIPTION
**Pull request by MCelliotG**
-Added battery values inside the battery icon, when values off, show bar instead.
- Small rearrangement of upper icons.
PLEASE REVIEW!

### CODE REVIEW

**Review by HyperDX — CHANGES_REQUESTED** [review]
I'd say that this green fillment that shows battery level would be the best if you do this vertically. Now it's horizontal and for me it doesn't look that good. Look at the indicator on the phone. This green fillment is going there from right to left :). 
Also I'd move voltage little bit right (to be center aligned). Overall that's a neat change. :) Maybe it's possible to show this green fillment and voltage or fillment and perecentage (depending on the setting in menu)?

**Comment by MCelliotG** [comment]
I tried to do this initially so that the values are above the fill but there were two issues, one there were drawing problems with changing values messing up the background, second since the bar is lessening, the value colour should be in a colour that looks good on both colored and black background. The battery went horizontal exactly because the values would not fit at all. Another idea would be to show the battery bar vertically only when values are off.

**Comment by MCelliotG** [comment]
I rushed to make these changes,as today my holiday begins and I'll be away from my PC for a week. Please feel free to adjust whatever is necessary.

**Comment by ohmytime** [comment]
I think this is a neat change, we can display the voltage value and percentage inside the battery without taking up other space. Which we could choose from the menu settings. As for the imperfections, we can improve them.

**Pull request merged**
